version: "3"
services: 
    frontend:
        build: ./MyBlog-Frontend
        ports: 
            - "3000:3000"
    backend:
        build: ./backend    
        ports: 
            - "5656:5656"
        volumes: 
            - ./MyBlog-Backend:/app