name: Linter
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: get dependencies
        run: cd ./Bloggie-Backend && npm install
      - name: lint
        uses: wearerequired/lint-action@v1
        run: cd ./Bloggie-Backend
        with:
          prettier: true
